version: '3'
services:
  frontend:
    volumes:
      - ./frontend:/app
    container_name: frontend
    env_file:
      - .env
    networks:
      - network
    restart: unless-stopped
    ports:
      - 3000:3000
    build: frontend
    depends_on:
      - backend


  backend:
    volumes:
        - ./backend:/app
    container_name: backend
    ports:
      - 3001:3001
    env_file:
      - .env
    networks:
      - network
    restart: unless-stopped
    build: backend
    depends_on:
      - postgres


  postgres:
    volumes:
      - data:/var/lib/postgresql/data
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 5050:80
    networks:
      - network
    depends_on:
      - postgres
    environment:
        PGADMIN_DEFAULT_EMAIL: transcendence@42paris.fr
        PGADMIN_DEFAULT_PASSWORD: transcendence

volumes:
  data:
    driver: local
    driver_opts:
      type : none
      o: bind
      device : /Users/jeancarlen/42_cursus/Trance-Dance/srcDocker/data

networks:
    network:
      driver: bridge


#   reference
#version: "3.9"

#services:

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    logging:
#      driver: none
#    volumes:
#      - ./docker/pgadmin_servers.json:/pgadmin4/servers.json

#   backend:
#     build:
#       cont/ext: ./docker
#       dockerfile: ./backend.dockerfile
#       volumes:
#         - ./backend:/app

#   frontend:
#     build:
#       context: ./docker
#       dockerfile: ./frontend.dockerfile
#     volumes:
#       - ./frontend:/app

# volumes:
#   data:

# networks:
#   backend:
# */
